import { ErrorCode, OrchestrationErrorBody } from './errors';

/** Canonical command envelope. `playerId` identifies the caller; gameplay faction is resolved separately. */
export interface CommandRequest {
  commandId: string;
  playerId: string;
  timestamp?: number;
  parameters?: Record<string, unknown>;
  clientContext?: Record<string, unknown>;
  /** Correlation id; generated by the orchestrator if omitted. */
  requestId?: string;
}

/** Alias retained for any transitional references. */
export type PlayerCommand = CommandRequest;

export type CommandCategory =
  | 'SYSTEM'
  | 'READ'
  | 'COMBAT'
  | 'ARMY'
  | 'TERRITORY'
  | 'ECONOMY'
  | 'DIPLOMACY'
  | 'WORLD'
  | 'AI'
  | 'FITNESS';

export type ParameterType = 'string' | 'number' | 'boolean' | 'string[]' | 'object';

export interface ParameterSpec {
  name: string;
  type: ParameterType;
  description: string;
}

export type CommandImplementationStatus = 'implemented' | 'unsupported';

export interface CommandDefinition {
  commandId: string;
  category: CommandCategory;
  description: string;
  requiredParameters: ParameterSpec[];
  optionalParameters: ParameterSpec[];
  validationRules: string[];
  routesTo: string[];
  changesState: boolean;
  requiresPhysicalEffort: boolean;
  synchronous: boolean;
  status: CommandImplementationStatus;
  possibleErrors: ErrorCode[];
}

export type StateChangeEntity =
  | 'territory'
  | 'army'
  | 'faction'
  | 'resources'
  | 'event'
  | 'visibility'
  | 'diplomacy'
  | 'commitment'
  | 'world';

export interface StateChange {
  entity: StateChangeEntity;
  id: string;
  field?: string;
  from?: unknown;
  to?: unknown;
  summary: string;
}

export interface ResourceChange {
  factionId: string;
  resource: string;
  from: number;
  to: number;
}

export interface TerritoryChange {
  territoryId: string;
  field: string;
  from: unknown;
  to: unknown;
}

export interface ArmyChange {
  armyId: string;
  field?: string;
  from?: unknown;
  to?: unknown;
  eliminated?: boolean;
}

export type GameEventKind =
  | 'battle'
  | 'territory'
  | 'army'
  | 'diplomacy'
  | 'imperial'
  | 'ai'
  | 'world'
  | 'system';

export interface GameEvent {
  kind: GameEventKind;
  id: string;
  title: string;
  summary: string;
  territoryId?: string | null;
  factionId?: string | null;
  data?: Record<string, unknown>;
}

export interface Notification {
  severity: 'info' | 'success' | 'warning' | 'error';
  title: string;
  body: string;
}

export interface PresentationCue {
  type: string;
  durationMs: number;
  title: string;
  summary: string;
  beats?: { atMs: number; text: string }[];
}

export interface AvailableAction {
  commandId: string;
  label: string;
  parametersHint?: Record<string, unknown>;
}

/** Standardized orchestrator output. Gameplay must not depend on wall-clock timestamps here. */
export interface CommandResponse {
  success: boolean;
  commandId: string;
  requestId: string;
  playerId: string;
  stateChanges: StateChange[];
  events: GameEvent[];
  notifications: Notification[];
  presentation: PresentationCue | null;
  resourcesChanged: ResourceChange[];
  territoriesChanged: TerritoryChange[];
  armiesChanged: ArmyChange[];
  newlyAvailableActions: AvailableAction[];
  errors: OrchestrationErrorBody[];
  payload: Record<string, unknown>;
}

export interface TraceStep {
  phase:
    | 'received'
    | 'validated'
    | 'routed'
    | 'engine_called'
    | 'engine_result'
    | 'state_applied'
    | 'output';
  atMs: number;
  detail: Record<string, unknown>;
}

export const DEFAULT_PRESENTATION_MS = 2500;

/** Internal handler return shape merged into CommandResponse by the orchestrator. */
export interface HandlerResult {
  stateChanges: StateChange[];
  events: GameEvent[];
  notifications: Notification[];
  presentation: PresentationCue | null;
  resourcesChanged: ResourceChange[];
  territoriesChanged: TerritoryChange[];
  armiesChanged: ArmyChange[];
  newlyAvailableActions: AvailableAction[];
  payload: Record<string, unknown>;
  /**
   * When false, the transaction still commits (e.g. a commitment is marked
   * failed) but CommandResponse.success is false.
   */
  commandSuccess?: boolean;
  errors?: OrchestrationErrorBody[];
}
