"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TERRAIN_NAMES = exports.PERSONALITY_NAMES = exports.ACTION_NAMES = exports.BALANCE = void 0;
exports.BALANCE = {
    scoring: {
        baseScores: {
            ATTACK: 40,
            DEFEND: 30,
            REINFORCE: 25,
            EXPAND: 35,
            SCOUT: 15,
            BUILD: 20,
            MOVE: 10,
            NEGOTIATE: 20,
            OFFER_PEACE: 25,
            DECLARE_WAR: 30,
            TRADE: 20,
            RETREAT: 15,
            WAIT: 5,
        },
        maxFactorWeight: 30,
        randomnessRange: 0.15,
        tiebreakerRandomness: 0.05,
        minReasonableScore: -100,
        maxScore: 200,
    },
    military: {
        advantageMultiplier: 1.5,
        defenderFortificationBonus: 0.3,
        defenderTerrainBonus: {
            plains: 0,
            forest: 0.1,
            coastal: 0.05,
            river: 0.15,
            mountain: 0.25,
            desert: -0.05,
            fortress: 0.4,
            hills: 0.12,
        },
        moraleModifier: 0.005,
        supplyModifier: 0.003,
        siegeValue: 2.5,
        knightValue: 3,
        soldierValue: 1,
        armyToGarrisonRatio: 1.5,
        criticalThreatRatio: 1.8,
        moderateThreatRatio: 1.3,
    },
    territory: {
        baseValueWeight: 1.0,
        resourceValueWeight: 1.2,
        strategicPositionWeight: 1.5,
        chokepointBonus: 25,
        capitalBonus: 50,
        capitalThreatMultiplier: 2.5,
        borderTerritoryBonus: 10,
        populationValuePerThousand: 2,
        fortificationCostPerLevel: {
            gold: 100,
            stone: 50,
            iron: 20,
        },
    },
    diplomacy: {
        opinionRange: 100,
        opinionAttackImpact: -40,
        opinionTerritoryLossImpact: -25,
        opinionTreatyBreakImpact: -50,
        opinionTradeImpact: 5,
        opinionAllianceImpact: 30,
        treatyHonorBonus: 8,
        trustDecayPerTurn: 0.5,
        allianceValue: 30,
        nonAggressionValue: 15,
        tradeAgreementValue: 10,
        warDeclarationOpinionHit: -30,
        peaceOfferReciprocity: 0.7,
    },
    economy: {
        goldWeight: 1.0,
        foodWeight: 0.8,
        ironWeight: 1.2,
        woodWeight: 0.6,
        stoneWeight: 0.5,
        resourceScarcityMultiplier: 1.5,
        buildEconomyThreshold: 0.3,
        tradeSurplusThreshold: 0.5,
        reinforcementCostPerSoldier: {
            gold: 5,
            food: 3,
        },
    },
    personality: {
        modifierRange: 2,
        extremePersonalityBonus: 1.5,
        riskPenaltyMultiplier: 10,
    },
    memory: {
        recentEventWeight: 1.0,
        eventDecayHalfLifeTurns: 15,
        maxMemoryEntriesPerFaction: 20,
        revengeBaseModifier: 0.4,
        trustworthinessImpact: 0.6,
    },
    goals: {
        maxActiveGoals: 5,
        highPriorityThreshold: 80,
        mediumPriorityThreshold: 40,
        goalAlignmentBonus: 20,
        goalMisalignmentPenalty: 15,
        progressBonusFactor: 0.3,
    },
    risk: {
        unacceptableRisk: 0.7,
        highRisk: 0.5,
        moderateRisk: 0.3,
        lowRisk: 0.15,
        riskPenaltyBase: 15,
    },
    simulate: {
        defaultTurns: 30,
        defaultSeed: 42,
        warlordDecisionDelayMs: 0,
    },
    combat: {
        baseStrength: {
            soldier: 1,
            knight: 4,
            siegeEngine: 6,
            garrison: 0.85,
        },
        numericalAdvantage: {
            scalingExponent: 0.85,
            maxRatioAdvantage: 2.5,
            minRatio: 0.25,
        },
        terrain: {
            attackerModifier: {
                plains: 1.0,
                mountain: 0.75,
                forest: 0.88,
                coastal: 0.95,
                desert: 0.97,
                river: 0.82,
                fortress: 0.8,
                hills: 0.92,
            },
            defenderModifier: {
                plains: 1.05,
                mountain: 1.5,
                forest: 1.2,
                coastal: 1.08,
                desert: 1.0,
                river: 1.3,
                fortress: 1.15,
                hills: 1.28,
            },
            attackerSiegePenaltyPerMountainLevel: 0.05,
            defenderRiverCrossingBonus: 1.18,
        },
        fortification: {
            perLevelStrengthBonus: 0.12,
            perLevelCasualtyReduction: 0.05,
            perLevelSiegeNeed: 2,
            maxLevel: 5,
            capitalBonus: 1.3,
            structureNames: {
                '0': 'Undefended',
                '1': 'Outpost',
                '2': 'Palisade Wall',
                '3': 'Stone Walls',
                '4': 'Castle',
                '5': 'Citadel / Fortress',
            },
        },
        morale: {
            highMoraleBonusPer10: 0.03,
            lowMoralePenaltyPer10: 0.05,
            rallyChancePerPositiveMorale: 0.002,
            routeThreshold: 25,
        },
        supply: {
            lowSupplyPenaltyPer10: 0.02,
            criticalSupplyThreshold: 20,
        },
        siege: {
            engineVsFortificationMultiplier: 1.0,
            noSiegeFortressMalus: 0.45,
            minSiegeNeededForFortress: 3,
        },
        unitType: {
            knightVsInfantryOpenTerrainBonus: 1.3,
            knightVsInfantryDenseTerrainMalus: 0.8,
            siegeOnlyUsefulAttack: true,
            garrisonBonusWhenDefending: 1.25,
        },
        randomness: {
            range: 0.18,
            perPhaseRange: 0.08,
            seedSaltBase: 982451653,
        },
        casualties: {
            baseRate: 0.18,
            intensityMultiplier: 1.4,
            winnerCasualtyMultiplier: 0.65,
            loserCasualtyMultiplier: 1.25,
            closeBattleExtraCasualties: 0.1,
            routCasualtyMultiplier: 1.9,
            fortificationDefenderCasualtyReduction: 0.06,
            minCasualtyRate: 0.03,
            maxCasualtyRate: 0.95,
            decisiveWinnerSurplusPct: 0.75,
        },
        retreat: {
            baseSurvivalRate: 0.55,
            perMoraleSurvival: 0.003,
            cavalryBoostRetreat: 0.15,
            fortressGarrisonRetreatSurvival: 0.85,
            enemyCloseRetreatMalus: 0.2,
            criticalRetreatThreshold: 0.4,
        },
        victory: {
            decisiveRatioThreshold: 1.7,
            narrowRatioThreshold: 1.1,
            pyrrhicWinnerCasualtyRate: 0.33,
            stalemateMaxRatio: 1.05,
            stalemateMaxMargin: 0.03,
            mutualLossThreshold: 0.45,
            captureRequiredAdvantage: 1.15,
            captureCapitalRequirement: 1.4,
        },
        phases: {
            count: 3,
            names: ['Skirmish Phase', 'Main Assault', 'Final Clash'],
            weights: [0.25, 0.45, 0.3],
        },
        battleEvents: {
            flankChance: 0.12,
            ambushChance: 0.08,
            breachChancePerSiege: 0.06,
            rallyChance: 0.1,
            heroicStandChance: 0.07,
            criticalHitChance: 0.1,
        },
    },
    mapGen: {
        initial: {
            defaultSeed: 42,
            defaultInitialTerritories: 18,
            defaultInitialRegions: 4,
            defaultStartingTerritoriesPerFaction: 3,
            defaultMinCapitalsDistance: 4,
            defaultFrontierSlotsBuffer: 2,
            maxStartSearchAttempts: 50,
        },
        territory: {
            minNeighbors: 2,
            maxNeighbors: 6,
            avgNeighbors: 3.6,
            neighborConnectJitter: 0.35,
            fortificationCapitalDefault: 4,
            fortificationStartDefault: 1,
            garrisonCapitalBase: 500,
            garrisonStartBase: 180,
            garrisonNeutralBase: 80,
            capitalBaseValueMin: 50,
            capitalBaseValueMax: 75,
            resourceDensityRoll: 0.55,
            minResourcesPerTerritory: 1,
            maxResourcesPerTerritory: 3,
            populationScaleByValue: 500,
            populationJitter: 0.25,
            strategicChokepointBonus: 0.3,
        },
        growth: {
            expansionDefaultTerritories: 4,
            expansionMin: 1,
            expansionMax: 8,
            newRegionEveryNTerritories: 5,
            regionTargetSize: { min: 3, max: 8, ideal: 5 },
            frontierConnectionRetries: 12,
            overlapPreventionRadius: 1,
            minConnectsToExisting: 1,
            idealConnectsToExisting: 2,
            crossNeighborChance: 0.35,
        },
        themes: {
            defaultRarity: 1,
            rarityWeightingExponent: 1.2,
            sameThemeBiasWhenAdjacent: 2.5,
            transitionSmoothingFactor: 0.4,
            coastalBiasPlacementBoost: 1.8,
            regionThemePersistence: 0.7,
        },
        naming: {
            disambiguationSalt: 1000,
            nameRetriesUntilUnique: 30,
            capitalSuffixBias: 1.5,
        },
        fogOfWar: {
            defaultRevealRangeFromControl: 1,
            scoutedDecayTurns: 8,
            discoveredNeverForgets: true,
            revealOnConquestRange: 1,
        },
        graph: {
            hexGridPerturbation: 0.45,
            ringPlacementVariance: 0.3,
            neighborDistanceThreshold: 1.9,
            diagonalNeighborThreshold: 1.45,
            minDistanceBetweenCapitals: 3,
        },
        resources: {
            goldBaseWeight: 1,
            foodBaseWeight: 1.4,
            ironBaseWeight: 0.8,
            woodBaseWeight: 1.1,
            stoneBaseWeight: 0.7,
            perResourceJitter: 0.35,
            terrainResourceBoostFactor: 2.2,
        },
    },
};
exports.ACTION_NAMES = {
    ATTACK: 'Attack',
    DEFEND: 'Defend',
    REINFORCE: 'Reinforce',
    EXPAND: 'Expand',
    SCOUT: 'Scout',
    BUILD: 'Fortify',
    MOVE: 'Move troops',
    NEGOTIATE: 'Negotiate',
    OFFER_PEACE: 'Offer peace',
    DECLARE_WAR: 'Declare war',
    TRADE: 'Trade',
    RETREAT: 'Retreat',
    WAIT: 'Wait',
};
exports.PERSONALITY_NAMES = {
    defensive: 'Defensive',
    aggressive: 'Aggressive',
    expansionist: 'Expansionist',
    opportunistic: 'Opportunistic',
    diplomatic: 'Diplomatic',
    economic: 'Economic',
};
exports.TERRAIN_NAMES = {
    plains: 'Plains',
    mountain: 'Mountains',
    hills: 'Hills',
    forest: 'Forest',
    coastal: 'Coastal',
    desert: 'Desert',
    river: 'Riverlands',
    fortress: 'Fortress',
};
//# sourceMappingURL=balance.js.map