export const BALANCE = {
  scoring: {
    baseScores: {
      ATTACK: 40,
      DEFEND: 30,
      REINFORCE: 25,
      EXPAND: 35,
      SCOUT: 15,
      BUILD: 20,
      MOVE: 10,
      NEGOTIATE: 20,
      OFFER_PEACE: 25,
      DECLARE_WAR: 30,
      TRADE: 20,
      RETREAT: 15,
      WAIT: 5,
    },
    maxFactorWeight: 30,
    randomnessRange: 0.15,
    tiebreakerRandomness: 0.05,
    minReasonableScore: -100,
    maxScore: 200,
  },
  military: {
    advantageMultiplier: 1.5,
    defenderFortificationBonus: 0.3,
    defenderTerrainBonus: {
      plains: 0,
      forest: 0.1,
      coastal: 0.05,
      river: 0.15,
      mountain: 0.25,
      desert: -0.05,
      fortress: 0.4,
      hills: 0.12,
    } as Record<string, number>,
    moraleModifier: 0.005,
    supplyModifier: 0.003,
    siegeValue: 2.5,
    knightValue: 3,
    soldierValue: 1,
    armyToGarrisonRatio: 1.5,
    criticalThreatRatio: 1.8,
    moderateThreatRatio: 1.3,
  },
  territory: {
    baseValueWeight: 1.0,
    resourceValueWeight: 1.2,
    strategicPositionWeight: 1.5,
    chokepointBonus: 25,
    capitalBonus: 50,
    capitalThreatMultiplier: 2.5,
    borderTerritoryBonus: 10,
    populationValuePerThousand: 2,
    fortificationCostPerLevel: {
      gold: 100,
      stone: 50,
      iron: 20,
    },
  },
  diplomacy: {
    opinionRange: 100,
    opinionAttackImpact: -40,
    opinionTerritoryLossImpact: -25,
    opinionTreatyBreakImpact: -50,
    opinionTradeImpact: 5,
    opinionAllianceImpact: 30,
    treatyHonorBonus: 8,
    trustDecayPerTurn: 0.5,
    allianceValue: 30,
    nonAggressionValue: 15,
    tradeAgreementValue: 10,
    warDeclarationOpinionHit: -30,
    peaceOfferReciprocity: 0.7,
  },
  economy: {
    goldWeight: 1.0,
    foodWeight: 0.8,
    ironWeight: 1.2,
    woodWeight: 0.6,
    stoneWeight: 0.5,
    resourceScarcityMultiplier: 1.5,
    buildEconomyThreshold: 0.3,
    tradeSurplusThreshold: 0.5,
    reinforcementCostPerSoldier: {
      gold: 5,
      food: 3,
    },
  },
  personality: {
    modifierRange: 2,
    extremePersonalityBonus: 1.5,
    riskPenaltyMultiplier: 10,
  },
  memory: {
    recentEventWeight: 1.0,
    eventDecayHalfLifeTurns: 15,
    maxMemoryEntriesPerFaction: 20,
    revengeBaseModifier: 0.4,
    trustworthinessImpact: 0.6,
  },
  goals: {
    maxActiveGoals: 5,
    highPriorityThreshold: 80,
    mediumPriorityThreshold: 40,
    goalAlignmentBonus: 20,
    goalMisalignmentPenalty: 15,
    progressBonusFactor: 0.3,
  },
  risk: {
    unacceptableRisk: 0.7,
    highRisk: 0.5,
    moderateRisk: 0.3,
    lowRisk: 0.15,
    riskPenaltyBase: 15,
  },
  simulate: {
    defaultTurns: 30,
    defaultSeed: 42,
    warlordDecisionDelayMs: 0,
  },

  combat: {
    unitStrength: {
      soldier: 1,
      knight: 4,
      siegeEngine: 6,
      garrison: 1,
    },
    morale: {
      broken: 0.60,
      low: 0.80,
      normal: 1.00,
      high: 1.10,
      excellent: 1.20,
    },
    defenseBonus: {
      openGround: 1.00,
      favorableTerrain: 1.10,
      strongTerrain: 1.20,
      fortified: 1.30,
    },
    terrainToDefenseBonus: {
      plains: 1.00,
      desert: 1.00,
      coastal: 1.05,
      hills: 1.10,
      forest: 1.12,
      river: 1.15,
      mountain: 1.20,
      fortress: 1.25,
    } as Record<string, number>,
    fortificationPerLevelBonus: 0.03,
    capitalBonus: 1.10,
    qualityDefault: 1.0,
    moraleToMultiplier(morale0_100: number): number {
      const m = morale0_100;
      if (m <= 20) return BALANCE.combat.morale.broken;
      if (m <= 40) return BALANCE.combat.morale.low;
      if (m <= 70) return BALANCE.combat.morale.normal;
      if (m <= 88) return BALANCE.combat.morale.high;
      return BALANCE.combat.morale.excellent;
    },
    casualties: {
      winnerBaseRate: 0.15,
      loserBaseRate: 0.40,
      winnerDominanceScale: 1.0,
      loserDominanceScale: 1.0,
      winnerMinRate: 0.005,
      winnerMaxRate: 0.25,
      loserMinRate: 0.15,
      loserMaxRate: 0.98,
      closeBattleExtraWinner: 0.02,
      closeBattleExtraLoser: 0.02,
      closeBattleThreshold: 0.08,
      randomJitter: 0.02,
    },
    randomness: {
      seedSaltBase: 982451653,
      upsetRange: 0.02,
    },
    victory: {
      narrowWinnerMaxAdvantage: 0.15,
      decisiveWinnerMinAdvantage: 0.50,
      pyrrhicWinnerCasualtyThreshold: 0.22,
      captureRequiredWinnerAdvantage: 0.10,
      captureCapitalRequiredWinnerAdvantage: 0.25,
      captureMinAttackerRemainingRatio: 0.05,
    },
    retreat: {
      baseSurvivalRate: 0.55,
      perMoraleSurvival: 0.003,
      cavalryBoostRetreat: 0.15,
      fortressGarrisonRetreatSurvival: 0.85,
    },
    moraleDelta: {
      narrowWin: 6,
      normalWin: 10,
      decisiveWin: 16,
      pyrrhicWin: 3,
      narrowLoss: -8,
      normalLoss: -12,
      decisiveLoss: -20,
      pyrrhicLoss: -4,
      draw: 0,
    },
  },

  mapGen: {
    initial: {
      defaultSeed: 42,
      defaultInitialTerritories: 18,
      defaultInitialRegions: 4,
      defaultStartingTerritoriesPerFaction: 3,
      defaultMinCapitalsDistance: 4,
      defaultFrontierSlotsBuffer: 2,
      maxStartSearchAttempts: 50,
    },
    territory: {
      minNeighbors: 2,
      maxNeighbors: 6,
      avgNeighbors: 3.6,
      neighborConnectJitter: 0.35,
      fortificationCapitalDefault: 4,
      fortificationStartDefault: 1,
      garrisonCapitalBase: 500,
      garrisonStartBase: 180,
      garrisonNeutralBase: 80,
      capitalBaseValueMin: 50,
      capitalBaseValueMax: 75,
      resourceDensityRoll: 0.55,
      minResourcesPerTerritory: 1,
      maxResourcesPerTerritory: 3,
      populationScaleByValue: 500,
      populationJitter: 0.25,
      strategicChokepointBonus: 0.3,
    },
    growth: {
      expansionDefaultTerritories: 4,
      expansionMin: 1,
      expansionMax: 8,
      newRegionEveryNTerritories: 5,
      regionTargetSize: { min: 3, max: 8, ideal: 5 },
      frontierConnectionRetries: 12,
      overlapPreventionRadius: 1,
      minConnectsToExisting: 1,
      idealConnectsToExisting: 2,
      crossNeighborChance: 0.35,
    },
    themes: {
      defaultRarity: 1,
      rarityWeightingExponent: 1.2,
      sameThemeBiasWhenAdjacent: 2.5,
      transitionSmoothingFactor: 0.4,
      coastalBiasPlacementBoost: 1.8,
      regionThemePersistence: 0.7,
    },
    naming: {
      disambiguationSalt: 1000,
      nameRetriesUntilUnique: 30,
      capitalSuffixBias: 1.5,
    },
    fogOfWar: {
      defaultRevealRangeFromControl: 1,
      scoutedDecayTurns: 8,
      discoveredNeverForgets: true,
      revealOnConquestRange: 1,
    },
    graph: {
      hexGridPerturbation: 0.45,
      ringPlacementVariance: 0.3,
      neighborDistanceThreshold: 1.9,
      diagonalNeighborThreshold: 1.45,
      minDistanceBetweenCapitals: 3,
    },
    resources: {
      goldBaseWeight: 1,
      foodBaseWeight: 1.4,
      ironBaseWeight: 0.8,
      woodBaseWeight: 1.1,
      stoneBaseWeight: 0.7,
      perResourceJitter: 0.35,
      terrainResourceBoostFactor: 2.2,
    },
  },

  events: {
    world: {
      maxEventsPerTurn: 4,
      sameEventCooldownTurns: 6,
      sameTerritoryMaxConcurrentActive: 3,
      territoryChoiceMinPopulation: 2000,
      rngSalt: 0x5CA1AB1E,
    },
    severityWeights: {
      minor: 10,
      moderate: 5,
      severe: 2,
      critical: 0.6,
    } as Record<string, number>,
    severityConsequenceScales: {
      minor: 1.0,
      moderate: 1.8,
      severe: 2.8,
      critical: 4.2,
    } as Record<string, number>,
    defaultEventDuration: { min: 2, max: 6 },

    thresholds: {
      lowFactionStability: 55,
      criticalFactionStability: 30,
      lowTerritoryStability: 55,
      criticalTerritoryStability: 30,
      lowFoodRatio: 0.6,
      criticalFoodRatio: 0.3,
      lowPopulationForAgriculturalVulnerability: 5000,
      highTax: 0.65,
      goodProsperityRatio: 1.4,
      greatProsperityRatio: 1.8,
      strongTradeAccessNeighbors: 3,
      weakTradeAccessNeighbors: 0,
      borderHostileNeighbors: 1,
      desertionGarrisonLowMorale: 45,
    },

    trigger: {
      drought: { baseWeight: 1.2, plainsBoost: 1.6, desertBoost: 2.2 },
      flood: { baseWeight: 1.0, riverBoost: 2.4, coastalBoost: 1.5 },
      storm: { baseWeight: 0.8, coastalBoost: 2.2 },
      harshWinter: { baseWeight: 0.6, mountainBoost: 1.8, hillsBoost: 1.3 },
      resourceDiscovery: { baseWeight: 0.7, noResourceTerritoryBoost: 1.6 },
      foodShortage: { baseWeight: 2.0, droughtActiveBoost: 2.5, lowFoodReserveBoost: 2.2 },
      famine: { baseWeight: 1.0, foodShortageActiveBoost: 4.0, criticalFoodBoost: 3.0 },
      prosperity: { baseWeight: 1.2, goodTradeBoost: 1.8, stableBoost: 1.5 },
      tradeBoom: { baseWeight: 0.9, coastalBoost: 1.7, manyNeighborsBoost: 1.6 },
      unrest: { baseWeight: 2.0, stabilityLowBoost: 2.5, highTaxBoost: 1.8, famineActiveBoost: 3.0 },
      rebellion: { baseWeight: 0.8, unrestActiveBoost: 3.2, stabilityCriticalBoost: 2.8 },
      borderTension: { baseWeight: 1.2, hostileNeighborBoost: 2.5 },
    },

    chain: {
      droughtToFoodShortageProb: 0.55,
      droughtToFoodShortageDelayMin: 1,
      foodShortageToFamineProb: 0.35,
      foodShortageToFamineDelayMin: 1,
      famineToUnrestProb: 0.50,
      famineToUnrestDelayMin: 0,
      unrestToRebellionProb: 0.25,
      unrestToRebellionDelayMin: 1,
    },

    consequenceMagnitudes: {
      droughtFoodProductionPctPerSeverity: -0.10,
      droughtInfrastructurePctPerSeverity: -0.02,
      floodPopulationPctPerSeverity: -0.01,
      floodInfrastructurePctPerSeverity: -0.03,
      floodFoodProductionPctPerSeverity: 0.06,
      stormFoodProductionPctPerSeverity: -0.04,
      stormGarrisonDeltaAbsPerSeverity: -20,
      harshWinterStabilityDeltaPerSeverity: -3,
      harshWinterFoodProductionPctPerSeverity: -0.08,
      resourceDiscoveryGoldPerSeverity: 250,
      resourceDiscoveryResourceBoostPct: 0.30,
      foodShortageStabilityDeltaPerSeverity: -4,
      foodShortagePopulationDeltaAbsPerSeverity: -200,
      foodShortageMoraleDeltaArmy: -6,
      famineStabilityDeltaPerSeverity: -10,
      faminePopulationDeltaAbsPerSeverity: -1200,
      famineMoraleDeltaArmy: -12,
      prosperityStabilityDeltaPerSeverity: 4,
      prosperityResourceGainPerSeverity: { gold: 80, food: 80 },
      tradeBoomGoldPerSeverity: 160,
      tradeBoomFoodPerSeverity: 120,
      unrestStabilityDeltaPerSeverity: -5,
      unrestGarrisonMoraleDelta: -8,
      rebellionStabilityDeltaPerSeverity: -14,
      rebellionGarrisonDeltaPerSeverity: -120,
      borderTensionGarrisonMoraleDelta: -5,
      borderTensionStabilityDelta: -2,
    },

    choices: {
      importFoodCostGoldPerSeverity: { minor: 120, moderate: 260, severe: 520, critical: 1000 } as Record<string, number>,
      importFoodStabilityRestore: 6,
      emergencyReservesFoodCostPerSeverity: { minor: 120, moderate: 280, severe: 560, critical: 1100 } as Record<string, number>,
      emergencyReservesStabilityRestore: 4,
      reduceTaxesGoldPenaltyPerSeverity: { minor: 80, moderate: 180, severe: 360, critical: 700 } as Record<string, number>,
      reduceTaxesStabilityRestore: 8,
      ignoreFamineStabilityPenaltyPerSeverity: { minor: -4, moderate: -8, severe: -14, critical: -22 } as Record<string, number>,
      ignoreFamineChainProbBoost: 0.15,
      sendTroopsGarrisonCostPerSeverity: 80,
      sendTroopsStabilityRestorePerSeverity: 3,
    },
  },
};


export const ACTION_NAMES = {
  ATTACK: 'Attack',
  DEFEND: 'Defend',
  REINFORCE: 'Reinforce',
  EXPAND: 'Expand',
  SCOUT: 'Scout',
  BUILD: 'Fortify',
  MOVE: 'Move troops',
  NEGOTIATE: 'Negotiate',
  OFFER_PEACE: 'Offer peace',
  DECLARE_WAR: 'Declare war',
  TRADE: 'Trade',
  RETREAT: 'Retreat',
  WAIT: 'Wait',
};

export const PERSONALITY_NAMES = {
  defensive: 'Defensive',
  aggressive: 'Aggressive',
  expansionist: 'Expansionist',
  opportunistic: 'Opportunistic',
  diplomatic: 'Diplomatic',
  economic: 'Economic',
};

export const TERRAIN_NAMES: Record<string, string> = {
  plains: 'Plains',
  mountain: 'Mountains',
  hills: 'Hills',
  forest: 'Forest',
  coastal: 'Coastal',
  desert: 'Desert',
  river: 'Riverlands',
  fortress: 'Fortress',
};
