export {
  ExerciseId,
  WorkoutId,
  WORKOUT_DIFFICULTIES,
  WorkoutDifficulty,
  EXERCISE_TYPES,
  ExerciseType,
  BODY_SECTIONS,
  BodySection,
  WORKOUT_PURPOSES,
  WorkoutPurpose,
  WORKOUT_EXERCISE_ROLES,
  WorkoutExerciseRole,
  WORKOUT_DIFFICULTY_RANK,
  ExercisePrescription,
  ExerciseDefinition,
  WorkoutExercise,
  WorkoutDefinition,
  WorkoutValidationIssue,
  PrescriptionInput,
  PrescribedWorkoutExercise,
  WorkoutPersonalizationMetadata,
  PrescribedWorkout,
} from './types';

export { isWorkoutDifficulty, workoutDifficultyRank, parseWorkoutDifficulty } from './difficulty';
export {
  isExerciseType,
  isBodySection,
  isWorkoutExerciseRole,
  clonePrescription,
  skippableForExerciseType,
  expectedPrescriptionKind,
} from './guards';
export {
  validateExerciseDefinition,
  validateWorkoutDefinition,
  validateExerciseCatalog,
  validateWorkoutCatalog,
  cloneExerciseDefinition,
  cloneWorkoutDefinition,
} from './validation';
export {
  listExerciseDefinitions,
  getExerciseDefinition,
  exerciseCatalogById,
  listWorkoutDefinitions,
  getWorkoutDefinition,
} from './catalog';
export {
  WorkoutPrescriptionResolver,
  prescribeWorkoutBaseline,
  baselinePrescriptionResolver,
  clonePrescribedWorkout,
  clonePersonalizationMetadata,
} from './prescription';
export { WORKOUT_PURPOSE_AWARDS_REWARDS, isWorkoutPurpose } from './purpose';
export { systemClock, AdjustableClock } from './clock';
export type { SessionClock } from './clock';
export {
  WORKOUT_SESSION_STATES,
  EXERCISE_PERFORMANCE_STATUSES,
  WORKOUT_FEEDBACK_VALUES,
  WORKOUT_FEEDBACK_STATES,
  WORKOUT_FEEDBACK_PROMPT,
  WORKOUT_ABANDONMENT_REASONS,
  INTEGRITY_FLAG_TYPES,
  WORKOUT_SESSION_ERROR_CODES,
  VALID_SESSION_TRANSITIONS,
  isTerminalSessionState,
  canTransitionSession,
  cloneWorkoutSession,
  cloneSessionPrescribedWorkout,
  totalPausedMs,
  createWorkoutSession,
  startWorkoutSession,
  beginWorkoutSession,
  pauseWorkoutSession,
  resumeWorkoutSession,
  abandonWorkoutSession,
  getCurrentExercise,
  completeExercise,
  skipExercise,
  isWorkoutFeedbackValue,
  submitWorkoutFeedback,
  recordIntegrityFlag,
  isEligibleForFitnessEvaluation,
  buildWorkoutSessionSummary,
  finalizeCompletedWorkout,
} from './session';
export type {
  WorkoutSessionId,
  WorkoutSessionState,
  ExercisePerformanceStatus,
  WorkoutFeedbackValue,
  WorkoutFeedbackState,
  WorkoutAbandonmentReason,
  IntegrityFlagType,
  ExerciseActualPerformance,
  SessionPrescribedExercise,
  SessionPrescribedWorkout,
  ExercisePerformance,
  PauseInterval,
  WorkoutIntegrityFlag,
  WorkoutFeedbackRecord,
  WorkoutSession,
  WorkoutGameplayContext,
  WorkoutSessionSummaryExercise,
  WorkoutSessionSummary,
  CompletedWorkoutRecord,
  WorkoutSessionErrorCode,
  WorkoutSessionError,
  SessionOpResult,
  CreateWorkoutSessionInput,
  CompleteExerciseInput,
  RecordIntegrityFlagInput,
} from './session';
export {
  FITNESS_EVIDENCE_VERSION,
  FITNESS_EVIDENCE_SOURCES,
  EVIDENCE_QUALITIES,
  FEEDBACK_RELATIVE_OFFSET,
  RELATIVE_DIFFICULTY_READINGS,
  FITNESS_EVALUATION_ERROR_CODES,
  validateCompletedWorkoutRecord,
  isEligibleCompletedWorkoutRecord,
  validateFitnessEvidence,
  cloneFitnessEvidence,
  evaluateFitnessEvidence,
  evaluateSessionFitnessEvidence,
} from './evaluation';
export type {
  FitnessEvidenceSource,
  EvidenceQuality,
  RelativeDifficultyReading,
  FitnessEvaluationContext,
  PerceivedDifficultyEvidence,
  CompletionPerformanceEvidence,
  RepSpeedEvidence,
  WorkloadEvidence,
  RestSkippingEvidence,
  BodySectionEvidence,
  FrequencyEvidence,
  RegroupingEvidence,
  FitnessEvidenceComponents,
  FitnessEvidence,
  FitnessEvaluationIssue,
  FitnessEvaluationErrorCode,
  FitnessEvaluationError,
  EvaluationOpResult,
} from './evaluation';
export {
  FITNESS_MODEL_VERSION,
  FITNESS_EVALUATION_VERSION,
  FITNESS_EVALUATION_CONFIG,
  MS_PER_DAY,
  MS_PER_WEEK,
  MS_PER_MONTH,
  FITNESS_ESTIMATE_ERROR_CODES,
  roundFitness,
  clampFitness,
  cloneFitnessEstimate,
  cloneFitnessEvaluationResult,
  validateFitnessEstimate,
  recencyFactor,
  decayConfidence,
  createInitialFitnessEstimate,
  evaluateFitness,
  applyFitnessEvaluation,
} from './estimate';
export type {
  FitnessNetDirection,
  FitnessBodySectionLevels,
  FitnessEstimate,
  FitnessHistoryContext,
  FitnessSourceContribution,
  FitnessFrequencySnapshot,
  FitnessEvaluationResult,
  CreateFitnessEstimateInput,
  FitnessEvaluationConfig,
  FitnessEstimateErrorCode,
  FitnessEstimateError,
  EstimateOpResult,
} from './estimate';
export {
  FITNESS_PERSONALIZATION_VERSION,
  FITNESS_PERSONALIZATION_CONFIG,
  FITNESS_PERSONALIZATION_ERROR_CODES,
  roundPersonalization,
  clampPersonalization,
  validatePersonalizationConfig,
  confidenceFactor,
  fitnessShiftFromLevel,
  difficultyShiftFromRanks,
  fitnessLevelForSection,
  computePersonalizationMapping,
  personalizationDecisionForStep,
  scaleRepetitions,
  scaleDurationSeconds,
  scaleExercisePrescription,
  personalizeWorkout,
} from './personalization';
export type {
  FitnessPersonalizationConfig,
  PersonalizationInput,
  PersonalizationMapping,
  PersonalizedExerciseDecision,
  FitnessPersonalizationErrorCode,
  FitnessPersonalizationError,
  PersonalizationOpResult,
} from './personalization';
export {
  PHYSICAL_RESULT_MODEL_VERSION,
  PHYSICAL_OUTPUT_VERSION,
  PHYSICAL_RESULT_CONFIG,
  PHYSICAL_RESULT_ERROR_CODES,
  roundPhysicalOutput,
  clampPhysicalOutput,
  difficultyFactor,
  exerciseModifier,
  clonePhysicalResult,
  validatePhysicalResultConfig,
  validatePhysicalResult,
  classifyPhysicalWork,
  contributeExercise,
  calculatePhysicalResult,
} from './physicalResult';
export type {
  PhysicalWorkClass,
  PhysicalExerciseContribution,
  PhysicalBodySectionOutput,
  PhysicalResult,
  PhysicalResultContext,
  PhysicalResultConfig,
  PhysicalResultErrorCode,
  PhysicalResultError,
  PhysicalResultOpResult,
} from './physicalResult';
