export * from './types';
export { BALANCE, ACTION_NAMES, PERSONALITY_NAMES, TERRAIN_NAMES } from './constants/balance';
export { SeededRNG } from './utils/SeededRNG';
export { PersonalitySystem } from './personality/PersonalitySystem';
export { MemorySystem, MemorySummary } from './memory/MemorySystem';
export { GoalSystem, GoalAlignmentResult, InitialGoalContext } from './goals/GoalSystem';
export { ScoringHelpers, ActionScorer, ScorerInput } from './scoring/ActionScorer';
export { DecisionEngine, WarlordState, validateCommitmentTarget, isActiveCommitmentStatus, cloneCommitment } from './engine/DecisionEngine';
export { EXECUTABLE_COMMITMENT_ACTIONS, UNSUPPORTED_COMMITMENT_ACTIONS, isExecutableCommitmentAction } from './engine/executableActions';
export { BattleEngine, BattleInput, BattleResult, BattleCalculation, BattleSideBreakdown, CasualtyBreakdown } from './battle/BattleEngine';
export {
  ArmyLike,
  TerritoryLike,
  UnitBreakdown,
  CombatPowerBreakdown,
  sumUnits,
  averageMorale,
  computeRawUnitPower,
  computeAttackerPower,
  computeDefenderPower,
  cityPresenceDefenseFactor,
  terrainAndFortToDefenseBonus,
  computeWinProbability,
  computeMilitaryAdvantageRatio,
} from './battle/CombatPower';
/** LEGACY TEST/DEMO ONLY. Not a production world authority. */
export { MapEngine } from './map/MapEngine';
export { collectNeighborGraphIssues, NeighborGraphIssue } from './map/graphInvariants';
/** LEGACY TEST/DEMO ONLY. Not production geography. */
export { NamingSystem } from './map/NamingSystem';
export { DEFAULT_THEME_LIBRARY, IRON_HILLS, CHRISTMAS_TREE_MOUNTAINS, TUNA_ISLES, EMBER_PLAINS, CRYSTAL_COAST, MISTWOOD, GOLDEN_DESERT } from './map/Themes';
/** LEGACY TEST FIXTURE. Production worlds use WorldCatalog + WorldDefinition. */
export { SimulationBuilder, SAMPLE_MAP, WARLORD_SPECS, MapTerritorySpec, WarlordSpec } from './simulation/SampleMap';
export {
  LabParams,
  BatchStats,
  ScenarioReport,
  buildLabInput,
  runBattleLabSingle,
  runBattleLabBatch,
  formatBatchStats,
  runBattleTestSuite,
  runSeededReproducibilityTest,
  runStatisticalSample,
  formatTestSuite,
} from './simulation/battleTests';
export {
  EXTREME_RATIO_SCENARIOS,
  EQUAL_FORCE_SCENARIOS,
  RATIO_SCENARIOS,
  RatioScenario,
  PropertyCheckResult,
  StressReport,
  runStressScenario,
  assertAttackerTroopMonotonicity,
  assertAttackerMoraleMonotonicity,
  assertDefenseBonusMonotonicity,
  runFullStressSuite,
  formatStressCsvReport,
} from './simulation/battleStressTests';

// ====== IMPERIAL EVENT & WORLD SIMULATION ENGINE ======
export {
  EventSeverity, SEVERITY_ORDER, EventCategory, EventStatus, EffectTarget, HistoryKind,
  ConditionContext, WorldHelper, TriggerScore, ImperialChoice, ConsequenceDelta,
  ChainDefinition, EventDefinition, ActiveEvent, TriggeredEvent, HistoryEntry,
  WorldStepInput, WorldStepOutput, EventConditionFn,
  buildDefaultSeverityTable, pickSeverityFromTable, severityScale, severityAtLeast,
} from './events/EventModel';
export {
  WorldHelperImpl, buildConditionContext, buildTriggerFn, COMMON_ELIGIBILITY,
  computeFactionStabilityModifier, candidateTerritoriesForEvents,
} from './events/EventTriggers';
export {
  EVENT_REGISTRY, EVENT_LIST, getEventById, getEventByTypeId, evaluateAllTriggersForTerritory,
} from './events/EventDefinitions';
export { WorldSimulator, ConsequenceApplier } from './events/WorldSimulator';

// ====== AUTHORITATIVE RUNTIME GAMESTATE ======
export { GameState, GAME_STATE_SCHEMA_VERSION, emptyWorldClock, emptyPlayerRewardState, emptyRewardApplicationState, emptyLevelDefeatState, emptyLevel1TutorialState, emptyTerritoryInfrastructure, createActiveInvasion } from './types/GameState';
export type {
  PlayerRewardState,
  PendingConstructionEffect,
  PendingGoldenYieldEffect,
  AppliedRewardRecord,
  ActiveInvasion,
  InvasionStatus,
  DefenseMobilizationAttachment,
  InvasionId,
  ConstructionProject,
  City,
  CityBuilding,
  TerritoryEconomy,
  TerritoryInfrastructure,
  PlayerFitnessState,
  PlayerEmpirePause,
  AttackerCooldown,
  LevelDefeatState,
  LevelDefeatStatus,
  Level1TutorialState,
  Level1TutorialBeat,
  Level1TutorialExpectedAction,
} from './types/GameState';
export {
  createGameState,
  createLegacySampleMapGameState,
  CreateGameStateOptions,
  CreateLegacySampleMapOptions,
  cloneGameState,
  checkGameStateInvariants,
  isGameStateStructurallyValid,
  GameStateInvariantViolation,
  toDecisionEngineSnapshot,
  toWorldStepInput,
  buildWarlordStates,
  rebindWarlordRuntime,
  syncCommitmentsFromWarlordStates,
} from './state';

export {
  WORLD_FORMAT_VERSION,
  WorldCatalog,
  DEFAULT_PRODUCTION_WORLD_ID,
  FIXTURE_TINY_WORLD_ID,
  FIXTURE_TINY_WORLD_RELATIVE_PATH,
  PRODUCTION_LEVEL_1_WORLD_ID,
  PRODUCTION_LEVEL_1_RELATIVE_PATH,
  FIXTURE_WORLD_REGISTRATIONS,
  PRODUCTION_WORLD_REGISTRATIONS,
  createWorldCatalog,
  createProductionWorldCatalog,
  formatWorldLoadFailure,
  identityFromDefinition,
  identityFromGameState,
  worldIdentitiesEqual,
  assertWorldIdentity,
  loadWorldDefinition,
  parseWorldJson,
  validateWorldDefinition,
  createGameStateFromWorld,
  applyImmutableWorldDefinition,
  loadTinyWorldDefinition,
  loadProductionLevel1Definition,
  requireWorldDefinition,
  resolveWorldDefinition,
  resolveWorldFilePath,
  getDefaultWorldCatalog,
  isLegacyDefinitionWorldId,
  regionDisplayName,
  tinyWorldJsonPath,
  productionLevel1JsonPath,
  serializeWorldDefinitionForClient,
} from './worldDefinition';
export type {
  WorldDefinition,
  RegionDefinition,
  TerritoryDefinition,
  WorldFactionDefinition,
  WorldPersonalityDefinition,
  WorldPolygon,
  ContainedWorldDefinition,
  WorldLoadResult,
  WorldFileRegistration,
  AuthoredWorldIdentity,
} from './worldDefinition';

// ====== ORCHESTRATOR (Phase 10) ======
export {
  Orchestrator,
  EngineRegistry,
  createDefaultRegistry,
  COMMAND_INDEX,
  getCommandDefinition,
  commandIndexSummary,
  MUTATING_HANDLERS,
  READ_ONLY_HANDLERS,
  ErrorCode,
  OrchestrationError,
} from './orchestration';
export type { CommandRequest, CommandResponse, StateChange } from './orchestration';

// ====== GAMEPLAY TELEMETRY (observes GameState; not a source of truth) ======
export {
  TELEMETRY_SCHEMA_VERSION,
  TELEMETRY_IMPORTANCE,
  TELEMETRY_EVENT_TYPES,
  importanceFor,
  isTelemetryEventType,
  createTelemetryEvent,
  validateTelemetryEvent,
  InMemoryTelemetryStore,
  IsolatedTelemetryRecorder,
  createTelemetryRecorder,
  collectCommandTelemetry,
  getEvents,
  eventsCausedBy,
  reconstructChain,
  summarizeGame,
  summarizePlayer,
  summarizeAi,
  derivedMetrics,
} from './analytics';
export type {
  TelemetryEvent,
  TelemetryEventType,
  TelemetryImportance,
  TelemetryQuery,
  TelemetryStore,
  TelemetryRecorder,
  GameTelemetrySummary,
  PlayerTelemetrySummary,
  AiTelemetrySummary,
} from './analytics';

// ====== CONTINUOUS WORLD (Phase 13) ======
export {
  ContinuousWorldEngine,
  parseElapsedTicks,
  runEventEngineTurn,
  commitmentDurationTicksFor,
  catchUpWorld,
  nextCatchUpElapsedTicks,
} from './world';
export type {
  WorldAdvanceResult,
  WorldSimulationHost,
  WorldTimeStamp,
  WorldAiDecisionRecord,
  WorldCommitmentProgressRecord,
  WorldCommitmentResolutionRecord,
  WorldEventStepResult,
  CatchUpWorldResult,
} from './world';

export {
  calculateMovementDuration,
  beginArmyMovement,
  progressArmyMovements,
  isArmyMoving,
  startStrategicAttack,
  selectDelayedAttackPlan,
  isLegalStagingTerritory,
} from './army';
export type { MovementDurationInput, MovementTickResult, DelayedAttackPlan } from './army';

// ====== FITNESS / WORKOUT DOMAIN (Phase 17A) ======
export {
  WORKOUT_DIFFICULTIES,
  EXERCISE_TYPES,
  BODY_SECTIONS,
  WORKOUT_PURPOSES,
  WORKOUT_EXERCISE_ROLES,
  WORKOUT_DIFFICULTY_RANK,
  WORKOUT_PURPOSE_AWARDS_REWARDS,
  isWorkoutDifficulty,
  workoutDifficultyRank,
  parseWorkoutDifficulty,
  isExerciseType,
  isBodySection,
  isWorkoutExerciseRole,
  isWorkoutPurpose,
  DEFAULT_SELECTED_WORKOUT_ID,
  WORKOUT_SELECTION_BY_PURPOSE,
  selectedWorkoutIdForPurpose,
  listPurposeWorkoutSelections,
  clonePrescription,
  skippableForExerciseType,
  expectedPrescriptionKind,
  validateExerciseDefinition,
  validateWorkoutDefinition,
  validateExerciseCatalog,
  validateWorkoutCatalog,
  cloneExerciseDefinition,
  cloneWorkoutDefinition,
  listExerciseDefinitions,
  getExerciseDefinition,
  exerciseCatalogById,
  listWorkoutDefinitions,
  getWorkoutDefinition,
  LIBRARY_DEFAULT_REPETITIONS,
  LIBRARY_DEFAULT_DURATION_SECONDS,
  LIBRARY_EXERCISES,
  LIBRARY_TEMPLATES,
  LIBRARY_REUSED_EXERCISE_IDS,
  LIBRARY_STRETCH_EXERCISE_IDS,
  ALL_STRETCH_EXERCISE_IDS,
  prescribeWorkoutBaseline,
  baselinePrescriptionResolver,
  clonePrescribedWorkout,
  clonePersonalizationMetadata,
  FITNESS_PERSONALIZATION_VERSION,
  FITNESS_PERSONALIZATION_CONFIG,
  personalizeWorkout,
  computePersonalizationMapping,
  confidenceFactor,
  scaleRepetitions,
  scaleDurationSeconds,
  systemClock,
  AdjustableClock,
  WORKOUT_SESSION_STATES,
  EXERCISE_PERFORMANCE_STATUSES,
  WORKOUT_FEEDBACK_VALUES,
  WORKOUT_FEEDBACK_STATES,
  WORKOUT_FEEDBACK_PROMPT,
  WORKOUT_ABANDONMENT_REASONS,
  INTEGRITY_FLAG_TYPES,
  isTerminalSessionState,
  canTransitionSession,
  cloneWorkoutSession,
  createWorkoutSession,
  startWorkoutSession,
  beginWorkoutSession,
  pauseWorkoutSession,
  resumeWorkoutSession,
  abandonWorkoutSession,
  getCurrentExercise,
  completeExercise,
  skipExercise,
  isWorkoutFeedbackValue,
  submitWorkoutFeedback,
  recordIntegrityFlag,
  isEligibleForFitnessEvaluation,
  buildWorkoutSessionSummary,
  finalizeCompletedWorkout,
  persistTerminalSessionHistory,
  FITNESS_EVIDENCE_VERSION,
  FITNESS_EVIDENCE_SOURCES,
  EVIDENCE_QUALITIES,
  FEEDBACK_RELATIVE_OFFSET,
  evaluateFitnessEvidence,
  evaluateSessionFitnessEvidence,
  isEligibleCompletedWorkoutRecord,
  cloneFitnessEvidence,
  FITNESS_MODEL_VERSION,
  FITNESS_EVALUATION_VERSION,
  FITNESS_EVALUATION_CONFIG,
  createInitialFitnessEstimate,
  evaluateFitness,
  applyFitnessEvaluation,
  cloneFitnessEstimate,
  recencyFactor,
  MS_PER_DAY,
  MS_PER_WEEK,
  PHYSICAL_RESULT_MODEL_VERSION,
  PHYSICAL_OUTPUT_VERSION,
  PHYSICAL_RESULT_CONFIG,
  calculatePhysicalResult,
  clonePhysicalResult,
  difficultyFactor,
} from './fitness';
export type {
  ExerciseId,
  WorkoutId,
  WorkoutDifficulty,
  ExerciseType,
  BodySection,
  WorkoutPurpose,
  WorkoutExerciseRole,
  ExercisePrescription,
  ExerciseDefinition,
  WorkoutExercise,
  WorkoutDefinition,
  WorkoutValidationIssue,
  PrescriptionInput,
  PrescribedWorkoutExercise,
  WorkoutPersonalizationMetadata,
  PrescribedWorkout,
  WorkoutPrescriptionResolver,
  PersonalizationInput,
  PersonalizationOpResult,
  FitnessPersonalizationConfig,
  SessionClock,
  WorkoutSessionId,
  WorkoutSessionState,
  ExercisePerformanceStatus,
  WorkoutFeedbackValue,
  WorkoutFeedbackState,
  WorkoutAbandonmentReason,
  IntegrityFlagType,
  ExerciseActualPerformance,
  SessionPrescribedWorkout,
  ExercisePerformance,
  WorkoutSession,
  WorkoutGameplayContext,
  WorkoutSessionSummary,
  CompletedWorkoutRecord,
  WorkoutSessionError,
  SessionOpResult,
  CreateWorkoutSessionInput,
  CompleteExerciseInput,
  FitnessEvidence,
  FitnessEvaluationContext,
  EvaluationOpResult,
  FitnessEstimate,
  FitnessHistoryContext,
  FitnessEvaluationResult,
  EstimateOpResult,
  PhysicalResult,
  PhysicalResultContext,
  PhysicalResultOpResult,
} from './fitness';

export {
  GAME_REWARD_MODEL_VERSION,
  GAME_REWARD_CONFIG_VERSION,
  GAME_REWARD_KINDS,
  GAME_REWARD_CONFIG,
  GAME_REWARD_ERROR_CODES,
  convertGameReward,
  convertTroops,
  convertConstructionWorkers,
  convertGoldenYield,
  convertDefense,
  cloneGameRewardResult,
  applyGameReward,
  REWARD_APPLICATION_MODEL_VERSION,
  REWARD_APPLICATION_ERROR_CODES,
  runWorkoutRewardPipeline,
  retryPendingWorkoutReward,
} from './rewards';
export {
  GAMEPLAY_CONFIG,
  ECONOMY_CONFIG,
  minutesToTicks,
  playerProtectionTicks,
  defenseResponseTicks,
  successfulDefenseRecoveryTicks,
  failedDefenseContinuationTicks,
  defenseWorkoutMaxDurationTicks,
  acceleratedRemainingTicks,
  startConstruction,
  consumeConstructionEffect,
  getConstructionProjectDefinition,
  listConstructionProjectTypes,
  isConstructionProjectType,
  syncAllFactionResourceIncome,
  deriveFactionResourceIncome,
  cityIdFor,
  ensureCity,
  cityCombatModifiersEnabled,
  territoryHasCity,
  combatDefenseMultiplier,
  defenseWorkoutMultiplier,
  withTerritoryCombatView,
  collectTerritoryYield,
  peekCollectibleResources,
  productionAccrued,
  effectiveResourceOutput,
  progressWorldEconomy,
  consumeEmpireFood,
  foodConsumptionDisabled,
  settleTerritoryOwnershipChange,
  territoryDestructionHasLosses,
  beginInvasionAgainstPlayer,
  resolveInvasionBattle,
  processInvasionTimeouts,
  progressExpiredInvasions,
  isDeadlineElapsed,
  isOpenInvasion,
  commitBankedTroopsAndAttack,
  canAiAttackPlayer,
  isPlayerProtected,
  setPlayerEmpirePause,
  isPlayerAnchorProtected,
  isPlayerAnchorProtectedOnSnapshot,
  isPlayerAnchorTerritory,
  playerOwnedAnchorTerritoryIds,
  playerOwnedNonAnchorTerritoryIds,
  assertAnchorAttackAllowed,
  bindLevelAnchors,
  applyPlayerTerritoryLoss,
  evaluateWorldCompletion,
  applyWorldCompletionCheck,
  bindLevel1Tutorial,
  syncLevel1Tutorial,
  serializeLevel1TutorialView,
  isLevel1TutorialApplicable,
  isLevel1TutorialAiSuppressed,
  tutorialExpectedWorkoutPurpose,
  LEVEL1_SCRIPTED_RAID_TROOPS,
  ANCHOR_PROTECTED_REASON,
  ANCHOR_PROTECTED_MESSAGE,
} from './gameplay';
export type {
  WorldCompletionView,
  FoodConsumptionResult,
  FoodConsumptionFactionResult,
  TerritoryDestructionReport,
  Level1TutorialPublicView,
} from './gameplay';
export type {
  GameRewardKind,
  TroopReward,
  ConstructionWorkerReward,
  GoldenYieldReward,
  DefenseMobilizationReward,
  GameRewardResult,
  ConvertGameRewardInput,
  GameRewardConfig,
  GameRewardError,
  RewardOpResult,
  RewardApplicationContext,
  RewardApplicationMode,
  RewardApplicationResult,
  RewardApplicationSuccess,
  RewardApplicationFailure,
  RewardApplicationErrorCode,
  ApplyGameRewardOutcome,
  WorkoutPipelineResult,
} from './rewards';

export {
  GAME_STATE_PERSISTENCE_FORMAT,
  DEFAULT_WORLD_ID,
  PersistenceError,
  isPersistenceError,
  encodePersistable,
  decodePersistable,
  serializeToJson,
  deserializeFromJson,
  jsonRoundTrip,
  migrateGameStatePayload,
  hydratePersistedPayload,
  snapshotGameState,
  InMemoryGameStateStore,
  FixedWorldTimeAuthority,
  resolveAuthoritativeTargetTick,
  commitAuthoritativePlayerWorld,
  syncPlayerWorld,
  initializePlayerWorld,
  ensurePlayerWorld,
  SUPABASE_DDL,
  SupabaseGameStateStore,
  worldRecordToRow,
  rowToWorldRecord,
  telemetryEventToRow,
  rowToTelemetryEvent,
} from './persistence';
export type {
  PersistedWorldRecord,
  GameStateStore,
  LoadWorldResult,
  SaveWorldResult,
  WorldTimeAuthority,
  SyncPlayerWorldInput,
  SyncPlayerWorldResult,
  InitializePlayerWorldOptions,
  InitializePlayerWorldResult,
  EnsurePlayerWorldOptions,
  EnsurePlayerWorldResult,
} from './persistence';

export {
  WORKOUT_HISTORY_FORMAT,
  InMemoryWorkoutHistoryStore,
  DEFAULT_HISTORY_LIMIT,
  toWorkoutHistoryEntry,
  fitnessHistoryContextFromStore,
} from './fitness';
export type {
  WorkoutHistoryEntry,
  WorkoutHistoryStore,
} from './fitness';


