export * from './types';
export { BALANCE, ACTION_NAMES, PERSONALITY_NAMES, TERRAIN_NAMES } from './constants/balance';
export { SeededRNG } from './utils/SeededRNG';
export { PersonalitySystem } from './personality/PersonalitySystem';
export { MemorySystem, MemorySummary } from './memory/MemorySystem';
export { GoalSystem, GoalAlignmentResult, InitialGoalContext } from './goals/GoalSystem';
export { ScoringHelpers, ActionScorer, ScorerInput } from './scoring/ActionScorer';
export { DecisionEngine, WarlordState, validateCommitmentTarget, isActiveCommitmentStatus, cloneCommitment } from './engine/DecisionEngine';
export { EXECUTABLE_COMMITMENT_ACTIONS, UNSUPPORTED_COMMITMENT_ACTIONS, isExecutableCommitmentAction } from './engine/executableActions';
export { BattleEngine, BattleInput, BattleResult, BattleCalculation, BattleSideBreakdown, CasualtyBreakdown } from './battle/BattleEngine';
export {
  ArmyLike,
  TerritoryLike,
  UnitBreakdown,
  CombatPowerBreakdown,
  sumUnits,
  averageMorale,
  computeRawUnitPower,
  computeAttackerPower,
  computeDefenderPower,
  computeWinProbability,
  computeMilitaryAdvantageRatio,
} from './battle/CombatPower';
export { MapEngine } from './map/MapEngine';
export { collectNeighborGraphIssues, NeighborGraphIssue } from './map/graphInvariants';
export { NamingSystem } from './map/NamingSystem';
export { DEFAULT_THEME_LIBRARY, IRON_HILLS, CHRISTMAS_TREE_MOUNTAINS, TUNA_ISLES, EMBER_PLAINS, CRYSTAL_COAST, MISTWOOD, GOLDEN_DESERT } from './map/Themes';
export { SimulationBuilder, SAMPLE_MAP, WARLORD_SPECS, MapTerritorySpec, WarlordSpec } from './simulation/SampleMap';
export {
  LabParams,
  BatchStats,
  ScenarioReport,
  buildLabInput,
  runBattleLabSingle,
  runBattleLabBatch,
  formatBatchStats,
  runBattleTestSuite,
  runSeededReproducibilityTest,
  runStatisticalSample,
  formatTestSuite,
} from './simulation/battleTests';
export {
  EXTREME_RATIO_SCENARIOS,
  EQUAL_FORCE_SCENARIOS,
  RATIO_SCENARIOS,
  RatioScenario,
  PropertyCheckResult,
  StressReport,
  runStressScenario,
  assertAttackerTroopMonotonicity,
  assertAttackerMoraleMonotonicity,
  assertDefenseBonusMonotonicity,
  runFullStressSuite,
  formatStressCsvReport,
} from './simulation/battleStressTests';

// ====== IMPERIAL EVENT & WORLD SIMULATION ENGINE ======
export {
  EventSeverity, SEVERITY_ORDER, EventCategory, EventStatus, EffectTarget, HistoryKind,
  ConditionContext, WorldHelper, TriggerScore, ImperialChoice, ConsequenceDelta,
  ChainDefinition, EventDefinition, ActiveEvent, TriggeredEvent, HistoryEntry,
  WorldStepInput, WorldStepOutput, EventConditionFn,
  buildDefaultSeverityTable, pickSeverityFromTable, severityScale, severityAtLeast,
} from './events/EventModel';
export {
  WorldHelperImpl, buildConditionContext, buildTriggerFn, COMMON_ELIGIBILITY,
  computeFactionStabilityModifier, candidateTerritoriesForEvents,
} from './events/EventTriggers';
export {
  EVENT_REGISTRY, EVENT_LIST, getEventById, getEventByTypeId, evaluateAllTriggersForTerritory,
} from './events/EventDefinitions';
export { WorldSimulator, ConsequenceApplier } from './events/WorldSimulator';

// ====== AUTHORITATIVE RUNTIME GAMESTATE ======
export { GameState, GAME_STATE_SCHEMA_VERSION, emptyWorldClock, emptyPlayerRewardState, emptyRewardApplicationState, createActiveInvasion } from './types/GameState';
export type {
  PlayerRewardState,
  PendingConstructionEffect,
  PendingGoldenYieldEffect,
  AppliedRewardRecord,
  ActiveInvasion,
  InvasionStatus,
  DefenseMobilizationAttachment,
  InvasionId,
  ConstructionProject,
  City,
  CityBuilding,
  TerritoryEconomy,
  PlayerFitnessState,
  PlayerEmpirePause,
  AttackerCooldown,
} from './types/GameState';
export {
  createGameState,
  CreateGameStateOptions,
  cloneGameState,
  checkGameStateInvariants,
  isGameStateStructurallyValid,
  GameStateInvariantViolation,
  toDecisionEngineSnapshot,
  toWorldStepInput,
  buildWarlordStates,
  rebindWarlordRuntime,
  syncCommitmentsFromWarlordStates,
} from './state';

// ====== ORCHESTRATOR (Phase 10) ======
export {
  Orchestrator,
  EngineRegistry,
  createDefaultRegistry,
  COMMAND_INDEX,
  getCommandDefinition,
  commandIndexSummary,
  ErrorCode,
  OrchestrationError,
} from './orchestration';
export type { CommandRequest, CommandResponse, StateChange } from './orchestration';

// ====== CONTINUOUS WORLD (Phase 13) ======
export {
  ContinuousWorldEngine,
  parseElapsedTicks,
  runEventEngineTurn,
  commitmentDurationTicksFor,
} from './world';
export type {
  WorldAdvanceResult,
  WorldSimulationHost,
  WorldTimeStamp,
  WorldAiDecisionRecord,
  WorldCommitmentProgressRecord,
  WorldCommitmentResolutionRecord,
  WorldEventStepResult,
} from './world';

export {
  calculateMovementDuration,
  beginArmyMovement,
  progressArmyMovements,
  isArmyMoving,
  startStrategicAttack,
  selectDelayedAttackPlan,
  isLegalStagingTerritory,
} from './army';
export type { MovementDurationInput, MovementTickResult, DelayedAttackPlan } from './army';

// ====== FITNESS / WORKOUT DOMAIN (Phase 17A) ======
export {
  WORKOUT_DIFFICULTIES,
  EXERCISE_TYPES,
  BODY_SECTIONS,
  WORKOUT_PURPOSES,
  WORKOUT_EXERCISE_ROLES,
  WORKOUT_DIFFICULTY_RANK,
  WORKOUT_PURPOSE_AWARDS_REWARDS,
  isWorkoutDifficulty,
  workoutDifficultyRank,
  parseWorkoutDifficulty,
  isExerciseType,
  isBodySection,
  isWorkoutExerciseRole,
  isWorkoutPurpose,
  clonePrescription,
  skippableForExerciseType,
  expectedPrescriptionKind,
  validateExerciseDefinition,
  validateWorkoutDefinition,
  validateExerciseCatalog,
  validateWorkoutCatalog,
  cloneExerciseDefinition,
  cloneWorkoutDefinition,
  listExerciseDefinitions,
  getExerciseDefinition,
  exerciseCatalogById,
  listWorkoutDefinitions,
  getWorkoutDefinition,
  prescribeWorkoutBaseline,
  baselinePrescriptionResolver,
  clonePrescribedWorkout,
  clonePersonalizationMetadata,
  FITNESS_PERSONALIZATION_VERSION,
  FITNESS_PERSONALIZATION_CONFIG,
  personalizeWorkout,
  computePersonalizationMapping,
  confidenceFactor,
  scaleRepetitions,
  scaleDurationSeconds,
  systemClock,
  AdjustableClock,
  WORKOUT_SESSION_STATES,
  EXERCISE_PERFORMANCE_STATUSES,
  WORKOUT_FEEDBACK_VALUES,
  WORKOUT_FEEDBACK_STATES,
  WORKOUT_FEEDBACK_PROMPT,
  WORKOUT_ABANDONMENT_REASONS,
  INTEGRITY_FLAG_TYPES,
  isTerminalSessionState,
  canTransitionSession,
  cloneWorkoutSession,
  createWorkoutSession,
  startWorkoutSession,
  beginWorkoutSession,
  pauseWorkoutSession,
  resumeWorkoutSession,
  abandonWorkoutSession,
  getCurrentExercise,
  completeExercise,
  skipExercise,
  isWorkoutFeedbackValue,
  submitWorkoutFeedback,
  recordIntegrityFlag,
  isEligibleForFitnessEvaluation,
  buildWorkoutSessionSummary,
  finalizeCompletedWorkout,
  FITNESS_EVIDENCE_VERSION,
  FITNESS_EVIDENCE_SOURCES,
  EVIDENCE_QUALITIES,
  FEEDBACK_RELATIVE_OFFSET,
  evaluateFitnessEvidence,
  evaluateSessionFitnessEvidence,
  isEligibleCompletedWorkoutRecord,
  cloneFitnessEvidence,
  FITNESS_MODEL_VERSION,
  FITNESS_EVALUATION_VERSION,
  FITNESS_EVALUATION_CONFIG,
  createInitialFitnessEstimate,
  evaluateFitness,
  applyFitnessEvaluation,
  cloneFitnessEstimate,
  recencyFactor,
  PHYSICAL_RESULT_MODEL_VERSION,
  PHYSICAL_OUTPUT_VERSION,
  PHYSICAL_RESULT_CONFIG,
  calculatePhysicalResult,
  clonePhysicalResult,
  difficultyFactor,
} from './fitness';
export type {
  ExerciseId,
  WorkoutId,
  WorkoutDifficulty,
  ExerciseType,
  BodySection,
  WorkoutPurpose,
  WorkoutExerciseRole,
  ExercisePrescription,
  ExerciseDefinition,
  WorkoutExercise,
  WorkoutDefinition,
  WorkoutValidationIssue,
  PrescriptionInput,
  PrescribedWorkoutExercise,
  WorkoutPersonalizationMetadata,
  PrescribedWorkout,
  WorkoutPrescriptionResolver,
  PersonalizationInput,
  PersonalizationOpResult,
  FitnessPersonalizationConfig,
  SessionClock,
  WorkoutSessionId,
  WorkoutSessionState,
  ExercisePerformanceStatus,
  WorkoutFeedbackValue,
  WorkoutFeedbackState,
  WorkoutAbandonmentReason,
  IntegrityFlagType,
  ExerciseActualPerformance,
  SessionPrescribedWorkout,
  ExercisePerformance,
  WorkoutSession,
  WorkoutGameplayContext,
  WorkoutSessionSummary,
  CompletedWorkoutRecord,
  WorkoutSessionError,
  SessionOpResult,
  CreateWorkoutSessionInput,
  CompleteExerciseInput,
  FitnessEvidence,
  FitnessEvaluationContext,
  EvaluationOpResult,
  FitnessEstimate,
  FitnessHistoryContext,
  FitnessEvaluationResult,
  EstimateOpResult,
  PhysicalResult,
  PhysicalResultContext,
  PhysicalResultOpResult,
} from './fitness';

export {
  GAME_REWARD_MODEL_VERSION,
  GAME_REWARD_CONFIG_VERSION,
  GAME_REWARD_KINDS,
  GAME_REWARD_CONFIG,
  GAME_REWARD_ERROR_CODES,
  convertGameReward,
  convertTroops,
  convertConstructionWorkers,
  convertGoldenYield,
  convertDefense,
  cloneGameRewardResult,
  applyGameReward,
  REWARD_APPLICATION_MODEL_VERSION,
  REWARD_APPLICATION_ERROR_CODES,
  runWorkoutRewardPipeline,
} from './rewards';
export {
  GAMEPLAY_CONFIG,
  ECONOMY_CONFIG,
  minutesToTicks,
  playerProtectionTicks,
  defenseResponseTicks,
  successfulDefenseRecoveryTicks,
  failedDefenseContinuationTicks,
  defenseWorkoutMaxDurationTicks,
  acceleratedRemainingTicks,
  startConstruction,
  consumeConstructionEffect,
  collectTerritoryYield,
  peekCollectibleResources,
  productionAccrued,
  progressWorldEconomy,
  settleTerritoryOwnershipChange,
  beginInvasionAgainstPlayer,
  resolveInvasionBattle,
  processInvasionTimeouts,
  progressExpiredInvasions,
  isDeadlineElapsed,
  isOpenInvasion,
  commitBankedTroopsAndAttack,
  canAiAttackPlayer,
  isPlayerProtected,
  setPlayerEmpirePause,
} from './gameplay';
export type {
  GameRewardKind,
  TroopReward,
  ConstructionWorkerReward,
  GoldenYieldReward,
  DefenseMobilizationReward,
  GameRewardResult,
  ConvertGameRewardInput,
  GameRewardConfig,
  GameRewardError,
  RewardOpResult,
  RewardApplicationContext,
  RewardApplicationMode,
  RewardApplicationResult,
  RewardApplicationSuccess,
  RewardApplicationFailure,
  RewardApplicationErrorCode,
  ApplyGameRewardOutcome,
  WorkoutPipelineResult,
} from './rewards';


